<?php
/**
 * Builds a CSV pricelist of the resolved price for every user against every product.
 *
 * This is the reusable core (no WP-CLI, cron, or admin coupling): it gathers users and
 * products from WordPress, resolves each user's effective price per product through the
 * {@see PriceEngine}, and streams the rows to a CSV file. {@see ExportModule} drives it
 * from WP-CLI, cron, and the settings-page "Send now" button.
 *
 * Row shape: display_name, roles, product, sku, resolved_price. One row per
 * (user, product) pair — a full price list for each user.
 *
 * @package WCPricebook
 */

namespace WCPricebook\Export;

use WCPricebook\Config;
use WCPricebook\PriceEngine;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Generates (and optionally emails) the per-user pricelist CSV.
 */
class PricelistExporter {

	/**
	 * CSV column headers, in order.
	 *
	 * @var array<int,string>
	 */
	const COLUMNS = array( 'display_name', 'roles', 'product', 'sku', 'resolved_price' );

	/**
	 * Config provider.
	 *
	 * @var Config
	 */
	private $config;

	/**
	 * Price engine.
	 *
	 * @var PriceEngine
	 */
	private $engine;

	/**
	 * Constructor.
	 *
	 * @param Config      $config Plugin config.
	 * @param PriceEngine $engine Price engine.
	 */
	public function __construct( Config $config, PriceEngine $engine ) {
		$this->config = $config;
		$this->engine = $engine;
	}

	/**
	 * Build one CSV row for a (user, product) pair.
	 *
	 * @param array{id:int,display_name:string,roles:array<int,string>} $user    User ref.
	 * @param array{id:int,name:string,sku:string}                      $product Product ref.
	 * @return array<int,string> [ display_name, roles, product, sku, resolved_price ]
	 */
	public function build_row( array $user, array $product ) {
		// The engine only needs the product ID; the proxy avoids reloading a full
		// WC_Product for every user.
		$price = $this->engine->effective_price( '', new ProductProxy( $product['id'] ), (int) $user['id'] );

		return array(
			(string) $user['display_name'],
			implode( ', ', isset( $user['roles'] ) && is_array( $user['roles'] ) ? $user['roles'] : array() ),
			(string) $product['name'],
			(string) $product['sku'],
			$this->format_price( $price ),
		);
	}

	/**
	 * Write the full pricelist CSV to a file. Returns the number of data rows written.
	 *
	 * @param string                       $file File path to write.
	 * @param array{roles?:array<int,string>} $args Optional: limit to these WP roles.
	 * @return int Data rows written.
	 * @throws \RuntimeException When the file cannot be opened for writing.
	 */
	public function write_csv( $file, array $args = array() ) {
		$handle = fopen( $file, 'w' );
		if ( false === $handle ) {
			throw new \RuntimeException( 'Unable to open export file for writing: ' . $file );
		}

		fputcsv( $handle, self::COLUMNS, ',', '"', '\\' );

		$roles    = isset( $args['roles'] ) && is_array( $args['roles'] ) ? $args['roles'] : $this->config->export()['roles'];
		$products = $this->gather_products();
		$count    = 0;

		foreach ( $this->gather_users( $roles ) as $user ) {
			foreach ( $products as $product ) {
				fputcsv( $handle, $this->build_row( $user, $product ), ',', '"', '\\' );
				$count++;
			}
		}

		fclose( $handle );
		return $count;
	}

	/**
	 * Write the pricelist to a temp file and email it as an attachment.
	 *
	 * @param string                       $recipient Recipient email.
	 * @param array{roles?:array<int,string>} $args      Optional export args.
	 * @return array{file:string,count:int,sent:bool}
	 * @throws \RuntimeException When the temp file cannot be created/written.
	 */
	public function run_and_email( $recipient, array $args = array() ) {
		$file  = $this->temp_file();
		$count = $this->write_csv( $file, $args );
		$sent  = $this->email_file( $recipient, $file, $count );

		return array(
			'file'  => $file,
			'count' => $count,
			'sent'  => $sent,
		);
	}

	/**
	 * Email an already-written CSV file as an attachment. Split out so the background
	 * (batched) runner can send the file it assembled across many requests.
	 *
	 * @param string $recipient Recipient email.
	 * @param string $file      CSV file path.
	 * @param int    $count     Row count (shown in the body).
	 * @return bool Whether wp_mail() accepted the message.
	 */
	public function email_file( $recipient, $file, $count ) {
		$blogname = wp_specialchars_decode( (string) get_option( 'blogname' ), ENT_QUOTES );
		$subject  = sprintf(
			/* translators: 1: site name, 2: date */
			__( '[%1$s] Pricebook pricelist export — %2$s', 'wc-pricebook' ),
			'' !== $blogname ? $blogname : 'WooCommerce',
			gmdate( 'Y-m-d' )
		);
		$body = sprintf(
			/* translators: %d: number of rows */
			__( 'Attached is the pricelist export (%d rows), one row per user and product. Generated by WC Pricebook.', 'wc-pricebook' ),
			(int) $count
		);

		return (bool) wp_mail( $recipient, $subject, $body, array(), array( $file ) );
	}

	/**
	 * The product refs (id, name, sku) to price — gathered once. Public so the
	 * background batch runner can capture the product list at the start of a run and
	 * reuse it across batches.
	 *
	 * @return array<int,array{id:int,name:string,sku:string}>
	 */
	public function product_refs() {
		return $this->gather_products();
	}

	/**
	 * One page of user refs for the given roles. Unlike {@see self::gather_users} (a
	 * generator that walks every user), this returns a single bounded page so a batch
	 * runner can process users a chunk at a time.
	 *
	 * @param array<int,string> $roles    Limit to these roles (empty = all users).
	 * @param int               $page     1-based page number.
	 * @param int               $per_page Users per page.
	 * @return array<int,array{id:int,display_name:string,roles:array<int,string>}>
	 */
	public function user_refs_page( array $roles, $page, $per_page ) {
		$query = array(
			'number'  => max( 1, (int) $per_page ),
			'paged'   => max( 1, (int) $page ),
			'orderby' => 'ID',
			'order'   => 'ASC',
		);
		if ( ! empty( $roles ) ) {
			$query['role__in'] = $roles;
		}

		/** This filter is documented in {@see self::gather_users}. */
		$query = apply_filters( 'wc_pricebook_export_user_query', $query, (int) $page );

		$refs = array();
		foreach ( get_users( $query ) as $user ) {
			$refs[] = array(
				'id'           => (int) $user->ID,
				'display_name' => (string) $user->display_name,
				'roles'        => isset( $user->roles ) && is_array( $user->roles ) ? array_values( $user->roles ) : array(),
			);
		}
		return $refs;
	}

	/**
	 * Create (or truncate) a CSV file and write just the header row. Used by the batch
	 * runner to start a fresh file that later batches append to.
	 *
	 * @param string $file File path.
	 * @return void
	 * @throws \RuntimeException When the file cannot be opened.
	 */
	public function init_csv( $file ) {
		$handle = fopen( $file, 'w' );
		if ( false === $handle ) {
			throw new \RuntimeException( 'Unable to open export file for writing: ' . $file );
		}
		fputcsv( $handle, self::COLUMNS, ',', '"', '\\' );
		fclose( $handle );
	}

	/**
	 * Append rows for a set of users (each priced against every product) to an existing
	 * CSV file. Returns the number of rows written.
	 *
	 * @param string                                                               $file     CSV path (already holds a header).
	 * @param array<int,array{id:int,display_name:string,roles:array<int,string>}> $users    User refs.
	 * @param array<int,array{id:int,name:string,sku:string}>                      $products Product refs.
	 * @return int Rows appended.
	 * @throws \RuntimeException When the file cannot be opened.
	 */
	public function append_rows( $file, array $users, array $products ) {
		$handle = fopen( $file, 'a' );
		if ( false === $handle ) {
			throw new \RuntimeException( 'Unable to open export file for appending: ' . $file );
		}
		$count = 0;
		foreach ( $users as $user ) {
			foreach ( $products as $product ) {
				fputcsv( $handle, $this->build_row( $user, $product ), ',', '"', '\\' );
				$count++;
			}
		}
		fclose( $handle );
		return $count;
	}

	/**
	 * Gather the products to price, as lightweight refs. Published products only;
	 * the wc_pricebook_export_product_ids filter is the escape hatch to narrow/reorder.
	 *
	 * @return array<int,array{id:int,name:string,sku:string}>
	 */
	private function gather_products() {
		$refs = array();
		$page = 1;

		do {
			$batch = function_exists( 'wc_get_products' )
				? wc_get_products(
					array(
						'status'  => 'publish',
						'limit'   => 500,
						'page'    => $page,
						'orderby' => 'ID',
						'order'   => 'ASC',
						'return'  => 'objects',
					)
				)
				: array();

			foreach ( $batch as $product ) {
				$refs[] = array(
					'id'   => (int) $product->get_id(),
					'name' => (string) $product->get_name(),
					'sku'  => (string) $product->get_sku(),
				);
			}
			$page++;
		} while ( count( $batch ) === 500 );

		/**
		 * Filters the product refs included in the pricelist export.
		 *
		 * @param array<int,array{id:int,name:string,sku:string}> $refs Product refs.
		 */
		return apply_filters( 'wc_pricebook_export_product_ids', $refs );
	}

	/**
	 * Gather the users to price, as lightweight refs. Every registered user, or only
	 * those in the given roles. Paged so a large user base does not exhaust memory.
	 *
	 * @param array<int,string> $roles Limit to these roles (empty = all users).
	 * @return \Generator<array{id:int,display_name:string,roles:array<int,string>}>
	 */
	private function gather_users( array $roles ) {
		$page = 1;

		do {
			$query = array(
				'number'  => 500,
				'paged'   => $page,
				'orderby' => 'ID',
				'order'   => 'ASC',
			);
			if ( ! empty( $roles ) ) {
				$query['role__in'] = $roles;
			}

			/**
			 * Filters the WP_User_Query args used to gather export users.
			 *
			 * @param array<string,mixed> $query Query args.
			 * @param int                 $page  Current page.
			 */
			$query = apply_filters( 'wc_pricebook_export_user_query', $query, $page );

			$users = get_users( $query );
			foreach ( $users as $user ) {
				yield array(
					'id'           => (int) $user->ID,
					'display_name' => (string) $user->display_name,
					'roles'        => isset( $user->roles ) && is_array( $user->roles ) ? array_values( $user->roles ) : array(),
				);
			}
			$page++;
		} while ( count( $users ) === 500 );
	}

	/**
	 * Format a resolved price for the CSV: numeric prices to two decimals, an empty
	 * price (hidden / "Call for Price") to an empty cell.
	 *
	 * @param mixed $price Resolved price.
	 * @return string
	 */
	private function format_price( $price ) {
		if ( '' === (string) $price || null === $price || ! is_numeric( $price ) ) {
			return '';
		}
		return number_format( (float) $price, 2, '.', '' );
	}

	/**
	 * Create a temp file path for the CSV with a readable attachment name.
	 *
	 * @return string
	 * @throws \RuntimeException When a temp file cannot be created.
	 */
	private function temp_file() {
		$dir  = function_exists( 'get_temp_dir' ) ? get_temp_dir() : sys_get_temp_dir() . '/';
		$name = 'wc-pricebook-pricelist-' . gmdate( 'Ymd-His' ) . '.csv';
		$file = rtrim( $dir, '/\\' ) . '/' . $name;

		if ( false === @touch( $file ) ) { // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
			throw new \RuntimeException( 'Unable to create export temp file: ' . $file );
		}
		return $file;
	}
}
